### PR TITLE
fix all warnings, major refactoring 

### LINKED ISSUE #45: fix warnings
check with yarn lint.
Plenty of warnings. goal: 0 warnings

### PR DESCRIPTION
**Pull request by anizeani**
closes #45 
In the future, do not leave uncommented code in master branch, unless there is a good reason for it and then specify it in the comment. The problem is we have so much commented code, that it becomes difficult to differentiate what was usefull and what not!
- removed all unused variables and unused imports in productive code
- fixed warnings
- fix ID instead of id error in console
- removed a lot of commented code

Now: No warnings, no errors

Note: I realized that my ERR_BLOCKED_BY_CLIENT errors were due to my addblocker (and only while developing on localhost, not on productive homepage). 
If you see such errors while developing, disable your adblocker to check

### CODE REVIEW

**Comment by mosonyi** [comment]
In chrome I can see this point but not it production
image

**Review by mosonyi — CHANGES_REQUESTED** [review]
I have built it locally and no error was found.
Tried the functionality as well->All good!
There's only a small thing (attached 1 screenshot to the comments).

**Comment by anizeani** [comment]
I fixed it, but its somewhat a hack. I don't know why, but the unused import "Contribute" was necessary to remove the white marker. 
I found another way around, by setting the font-size of the marker in the why class to 0. This means, that markers won't be seen on the why page, but since I guess there won't be any there, this is a better solution, than leaving an unused import, which someone eventually will remove and not understand why a marker will appear

**Comment by mosonyi** [comment]
I have checked, the dot disappeared, but the contribution doesn't work well now. The loader remains forever even successful contribution.
Here's a screenshot:
image

**Comment by anizeani** [comment]
Thanks for checking! I will check that, too!
I think I didnt have that problem when I checked

**Comment by anizeani** [comment]
@mosonyi  I couldn't recreate your error. Lets discuss this on the element chat

**Review by mosonyi — APPROVED** [review]
We went through the functionality and works well. 
Changes approved.

**Review by brenzi — APPROVED** [review]
just tested that it loads. if you checked the rest. fine for me

**Pull request merged**
